
name: Running

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Setup Python
        with:
          python-version: "3.x"
      - run: pip install --upgrade pip && pip install -r requirements.txt
        name: Install Dependency
      - run: python app.py
        name: Running Program